services:
  lupai-front-devcontainer:
    # network_mode: host
    image: lupai-front-devcontainer
    container_name: lupai-front-devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - DEVCONTAINER_USER=node
    volumes:
      - ..:/workspace:cached
    # This keeps the devcontainer running.
    entrypoint: ['tail', '-f', '/dev/null']
